Repository JBrabson/little-esty-shop, pull requests merged in 2021-06, with the labels that each got.

#42 Db setup
  Gemfile
  Gemfile.lock
  app/models/customer.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/models/item.rb
  app/models/merchant.rb
  app/models/transaction.rb
  db/migrate/20210602001307_create_customers.rb
  db/migrate/20210602012256_create_invoices.rb
  db/migrate/20210602013339_create_merchants.rb
  db/migrate/20210602014103_create_transactions.rb
  db/migrate/20210602020607_create_items.rb
  db/migrate/20210602020731_create_invoice_items.rb
  db/migrate/20210602022030_change_credit_card_data_type.rb
  db/schema.rb
  lib/tasks/csv_load.rake
  spec/factories/invoice_items.rb
  spec/factories/invoices.rb
  spec/factories/items.rb
  spec/factories/merchants.rb
  spec/factories/transactions.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/transaction_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: documentation

#43 Db setup part deux
  app/assets/images/schema_drawing.jpg
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/models/transaction.rb
  db/migrate/20210602012256_create_invoices.rb
  db/migrate/20210602014103_create_transactions.rb
  db/migrate/20210602020731_create_invoice_items.rb
  db/schema.rb
  lib/tasks/csv_load.rake
Labels: documentation, enhancement

#44 Create merchant items show page, as well as tests to go along with them
  app/controllers/merchant_items_controller.rb
  app/views/layouts/application.html.erb
  app/views/merchant_items/edit.html.erb
  app/views/merchant_items/show.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/.resultset.json.lock
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_asc.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_asc_disabled.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_both.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_desc.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_desc_disabled.png
  coverage/assets/0.12.3/application.css
  coverage/assets/0.12.3/application.js
  coverage/assets/0.12.3/colorbox/border.png
  coverage/assets/0.12.3/colorbox/controls.png
  coverage/assets/0.12.3/colorbox/loading.gif
  coverage/assets/0.12.3/colorbox/loading_background.png
  coverage/assets/0.12.3/favicon_green.png
  coverage/assets/0.12.3/favicon_red.png
  coverage/assets/0.12.3/favicon_yellow.png
  coverage/assets/0.12.3/images/ui-bg_flat_0_aaaaaa_40x100.png
  coverage/assets/0.12.3/images/ui-bg_flat_75_ffffff_40x100.png
  coverage/assets/0.12.3/images/ui-bg_glass_55_fbf9ee_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_65_ffffff_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_75_dadada_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_75_e6e6e6_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_95_fef1ec_1x400.png
  coverage/assets/0.12.3/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  coverage/assets/0.12.3/images/ui-icons_222222_256x240.png
  coverage/assets/0.12.3/images/ui-icons_2e83ff_256x240.png
  coverage/assets/0.12.3/images/ui-icons_454545_256x240.png
  coverage/assets/0.12.3/images/ui-icons_888888_256x240.png
  coverage/assets/0.12.3/images/ui-icons_cd0a0a_256x240.png
  coverage/assets/0.12.3/loading.gif
  coverage/assets/0.12.3/magnify.png
  coverage/index.html
  lib/tasks/csv_load.rake
  spec/features/merchant_items_show_spec.rb
Labels: enhancement

#45 Add tests for validations/relationships.
  app/models/invoice.rb
  app/models/item.rb
  app/models/merchant.rb
  app/models/transaction.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20210602013339_create_merchants.rb
  db/schema.rb
  lib/tasks/csv_load.rake
  spec/models/customer_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/transaction_spec.rb
Labels: enhancement

#46 Admin dashboard
  app/controllers/admin_controller.rb
  app/views/admin/index.html.erb
  config/routes.rb
  spec/features/admin/index_spec.rb
Labels: enhancement

#48 Create Merchant Dashboard; tests, MVCs.
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/merchant/invoices_controller.rb
  app/controllers/merchant/items_controller.rb
  app/controllers/merchants_controller.rb
  app/models/item.rb
  app/models/merchant.rb
  app/views/merchant/dashboard/index.html.erb
  app/views/merchant/items/index.html.erb
  config/routes.rb
  spec/features/merchants/dashboard_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#47 Add coverage in gitignore
  .gitignore
  config/routes.rb
Labels: bug

#49 Add to views and controller for merchant dashboard items/invoices links.
  app/controllers/merchant/invoices_controller.rb
  app/views/merchant/dashboard/index.html.erb
  app/views/merchant/items/index.html.erb
  spec/features/merchants/dashboard_spec.rb
Labels: enhancement

#50 Add validations for models.
  app/models/customer.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/models/transaction.rb
  app/views/merchant/invoices/index.html.erb
  spec/models/customer_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/transaction_spec.rb
Labels: enhancement

#51 Admin top customers
  app/controllers/admin_controller.rb
  app/models/customer.rb
  app/views/admin/index.html.erb
  spec/features/admin/index_spec.rb
Labels: Advanced AR, enhancement

#52 create merchant invoices controller and mercahnt items controller as …
  app/controllers/merchant/invoices_controller.rb
  app/controllers/merchant_items_controller.rb
  app/views/merchant/invoices/show.html.erb
  config/routes.rb
  spec/features/merchant_invoice_show_spec.rb
  spec/features/merchant_items_show_spec.rb
Labels: enhancement

#53 Merchant item show
  app/controllers/merchant_items_controller.rb
  app/models/invoice_item.rb
  app/models/item.rb
  app/models/merchant.rb
  app/views/merchant_items/index.html.erb
  app/views/merchant_items/new.html.erb
  config/routes.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20210603010727_add_column_to_items.rb
  db/schema.rb
  lib/tasks/csv_load.rake
  spec/features/merchant_items/index_spec.rb
Labels: enhancement

#54 Invoices not shipped
  app/controllers/admin_controller.rb
  app/models/invoice.rb
  app/views/admin/index.html.erb
  spec/features/admin/index_spec.rb
  spec/models/invoice_spec.rb
Labels: Advanced AR

#60 Admin invoice show 2
  app/controllers/admin/invoices_controller.rb
  app/models/invoice_item.rb
  app/views/admin/invoices/show.html.erb
  spec/features/admin/invoices/show_spec.rb
  spec/models/invoice_item_spec.rb
Labels: Advanced AR, enhancement

#63 Major refactoring
  app/models/invoice.rb
  spec/features/admin/index_spec.rb
  spec/features/admin/invoices/index_spec.rb
  spec/features/merchant_invoice_show_spec.rb
  spec/features/merchant_items/index_spec.rb
Labels: bug, documentation

#65 Refactor merchants files and folders
  app/controllers/merchant/items_controller.rb
  app/controllers/merchant_items_controller.rb
  app/models/merchant.rb
  app/views/merchant/items/edit.html.erb
  app/views/merchant/items/new.html.erb
  app/views/merchant/items/show.html.erb
  config/routes.rb
  spec/features/merchants/invoice/show_spec.rb
  spec/features/merchants/items/index_spec.rb
  spec/features/merchants/items/show_spec.rb
  spec/models/invoice_spec.rb
  spec/models/transaction_spec.rb
Labels: documentation, help wanted

#66 Admin inv total rev
  app/controllers/admin/invoices_controller.rb
  app/models/invoice.rb
  app/views/admin/invoices/show.html.erb
  spec/features/admin/invoices/show_spec.rb
Labels: ActiveRecord, enhancement

#68 Delete unnecessary folder and files
  app/views/merchant_items/edit.html.erb
  app/views/merchant_items/index.html.erb
  app/views/merchant_items/new.html.erb
  app/views/merchant_items/show.html.erb
Labels: documentation, duplicate

#72 Fix test issues that occurred from merge conflicts
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/merchant/invoices_controller.rb
  app/views/merchant/invoices/index.html.erb
  app/views/merchant/items/index.html.erb
  spec/features/merchant/dashboard_spec.rb
  spec/features/merchants/dashboard_spec.rb
Labels: bug, documentation

#73 Admin update invoice status
  app/controllers/admin/invoices_controller.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/views/admin/invoices/show.html.erb
  config/routes.rb
  spec/features/admin/invoices/show_spec.rb
  spec/features/merchants/dashboard_spec.rb
Labels: enhancement

#74 Refactor views
  app/models/invoice.rb
  app/views/admin/index.html.erb
  app/views/admin/invoices/show.html.erb
  config/routes.rb
  spec/features/admin/index_spec.rb
  spec/features/merchants/dashboard_spec.rb
Labels: documentation

#77 Fix tests
  spec/features/merchant/invoices_index_spec.rb
  spec/features/merchants/items/index_spec.rb
  spec/models/merchant_spec.rb
Labels: bug, documentation

#79 Refactor invoice_item model query and status select on show page
  app/models/invoice_item.rb
  app/views/admin/invoices/show.html.erb
  spec/features/admin/invoices/show_spec.rb
Labels: documentation, enhancement

#86 Refactor folders files
  app/controllers/admin/invoices_controller.rb
  app/controllers/admin/merchants_controller.rb
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/merchant/invoices_controller.rb
  app/controllers/merchant/items_controller.rb
  app/models/customer.rb
  app/models/invoice.rb
  app/models/item.rb
  app/models/merchant.rb
  app/views/admin/merchants/index.html.erb
  config/routes.rb
  spec/features/admin/merchant/index_spec.rb
  spec/features/merchant/dashboard_spec.rb
  spec/features/merchants/invoices/index_spec.rb
  spec/features/merchants/invoices/show_spec.rb
  spec/features/merchants/items/index_spec.rb
  spec/features/merchants/items/show_spec.rb
  spec/models/customer_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
Labels: bug, documentation, enhancement

#90 Update casing in enums to match CSV files
  app/controllers/admin/merchants_controller.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/views/admin/invoices/show.html.erb
  app/views/merchant/invoices/show.html.erb
  db/migrate/20210602013339_create_merchants.rb
  db/schema.rb
  spec/features/admin/invoices/show_spec.rb
  spec/features/merchants/dashboard_spec.rb
  spec/features/merchants/invoices/index_spec.rb
  spec/features/merchants/invoices/show_spec.rb
  spec/features/welcome/index_spec.rb
Labels: documentation
